services:
  api:
    image: vectorzhao/move-my-car-api:latest
    env_file:
      - .env
    environment:
      DATABASE_URL: file:/app/data/move-my-car.db
      CLIENT_URL: http://localhost:5200
    volumes:
      - ./data:/app/data
    ports:
      - '4000:4000'

  web:
    image: vectorzhao/move-my-car-web:latest
    depends_on:
      - api
    env_file:
      - .env
    ports:
      - '5200:5200'
