services:
  api:
    image: vectorzhao/move-my-car-api:latest
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    ports:
      - '${PORT:-4000}:${PORT:-4000}'

  web:
    image: vectorzhao/move-my-car-web:latest
    depends_on:
      - api
    env_file:
      - .env
    ports:
      - '${WEB_PORT:-5200}:5200'
