services:
  api:
    image: vectorzhao/move-my-car-api:latest
    container_name: move-my-car-api
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    ports:
      - '${PORT:-4000}:${PORT:-4000}'
    command: sh -c "npx prisma migrate deploy && npm run prisma:seed && node dist/server.js"

  web:
    image: vectorzhao/move-my-car-web:latest
    container_name: move-my-car-web
    depends_on:
      - api
    env_file:
      - .env
    ports:
      - '${WEB_PORT:-5200}:5200'
